## Workhours

In [1]:
import numpy as np
import pandas as pd
import datetime
from datetime import datetime
import networkx as nx

In [2]:
# load the dataset
df=pd.read_csv('../Data/pageneral.csv')

In [3]:

#Strip white spaces
df=df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [4]:
df['Originator']=df['Originator'].str.extract('(\d+)').astype(int)

In [6]:
df['Recipient']=df['Recipient'].str.extract('(\d+)').astype(int)

In [8]:
# load the dataset
ncs=pd.read_csv('../Data/ncs.csv')

In [9]:
#The Merger
df=pd.merge(df, ncs, on='Originator')

In [22]:
# load the Workhours dataset
wh=pd.read_csv('../Data/WorkHours.csv')

In [23]:
#Strip white spaces
wh=wh.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [24]:
wh['Originator']=wh['Originator'].str.extract('(\d+)').astype(int)

In [25]:
#The Merger
wh1=pd.merge(df, wh, on='Originator')

In [26]:
wh1

,Originator,Recipient,Date,TrustScore,ncs,department,level,location,gender,tenure,...,nwd14,nwd15,nwd16,nwd17,nwd18,nwd19,nwd20,nwd21,nwd22,nwd23
0,33,54,4/29/2020 16:41,23,55,TL,2,G,female,7,...,0,0,0,0,0,0,0,0,0,0
1,33,253,4/29/2020 6:46,0,55,TL,2,G,female,7,...,0,0,0,0,0,0,0,0,0,0
2,33,103,4/27/2020 12:34,15,55,TL,2,G,female,7,...,0,0,0,0,0,0,0,0,0,0
3,33,25,4/27/2020 12:34,25,55,TL,2,G,female,7,...,0,0,0,0,0,0,0,0,0,0
4,33,160,4/24/2020 5:00,0,55,TL,2,G,female,7,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9847,267,46,4/3/2020 5:38,0,9,TL,4,G,female,1,...,0,0,0,0,0,0,0,0,0,0
9848,267,69,3/27/2020 7:34,21,9,TL,4,G,female,1,...,0,0,0,0,0,0,0,0,0,0
9849,267,34,2/14/2020 4:11,0,9,TL,4,G,female,1,...,0,0,0,0,0,0,0,0,0,0
9850,180,112,4/13/2020 8:09,25,2,TL,3,G,female,1,...,0,0,0,0,0,0,0,0,0,0
9851,180,30,3/23/2020 6:05,33,2,TL,3,G,female,1,...,0,0,0,0,0,0,0,0,0,0

In [27]:
wh1.to_csv(r'workhours-With_network.csv', index = False)

In [29]:
wh.to_csv(r'workhours.csv', index = False)